cfg:
  name: small_span_aug
  global_batch_size: 16384
  micro_batch_size: 256
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  resume_from_checkpoint: null
  pipeline_model_parallel_split_rank: 0
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  megatron_amp_O2: false
  seq_length: 512
  max_position_embeddings: 512
  num_layers: 6
  hidden_size: 512
  ffn_hidden_size: 2048
  num_attention_heads: 8
  init_method_std: 0.02
  hidden_dropout: 0.1
  attention_dropout: 0.1
  kv_channels: null
  apply_query_key_layer_scaling: true
  layernorm_epsilon: 1.0e-05
  persist_layer_norm: true
  gradient_as_bucket_view: true
  bias_gelu_fusion: true
  masked_softmax_fusion: true
  bias_dropout_add_fusion: true
  bias: true
  normalization: layernorm
  encoder_arch: transformer
  decoder_arch: transformer
  activation: gelu
  headscale: false
  share_word_embeddings: true
  share_decoder_tokens_head_embeddings: false
  tokenizer:
    library: regex
    type: null
    model: nemo:f4511a31569943ff909607eaee4f6668_megamolbart.model
    vocab_file: nemo:8bd356169fbe4824b9bf13ecdea37a8a_megamolbart.vocab
    merge_file: null
  data:
    dataset_path: /data/zinc_csv_split
    dataset:
      train: x[000..146]
      test: x[000..146]
      val: x[000..146]
    newline_int: 10
    header_lines: 1
    data_col: 1
    data_sep: ','
    sort_dataset_paths: true
    skip_lines: 0
    micro_batch_size: 256
    encoder_augment: true
    encoder_mask: true
    decoder_augment: true
    decoder_mask: false
    canonicalize_input: true
    dataloader_type: single
    drop_last: false
    pin_memory: false
    num_workers: 10
    links_file: /opt/nvidia/nemo_chem/examples/chem/conf/dataset/ZINC-downloader-test.txt
    mask_scheme: span
    mask_prob: 0.1
    span_lambda: 3.0
    num_enumerations: 5
    dataset_format: csv
  optim:
    name: fused_adam
    lr: 1.0
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.01
    sched:
      name: NoamAnnealing
      d_model: 512
      warmup_steps: 8000
      warmup_ratio: null
      max_steps: 1000000
      min_lr: 1.0e-05
  precision: 16
  target: nemo_chem.models.megamolbart.megamolbart_model.MegaMolBARTModel
  nemo_version: 1.11.0rc0
